# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

p_ggum_impl <- function(thetas, params) {
    .Call(`_mupp_p_ggum_impl`, thetas, params)
}

pder1_theta_ggum_impl <- function(thetas, params) {
    .Call(`_mupp_pder1_theta_ggum_impl`, thetas, params)
}

p_mupp_impl <- function(thetas_s, thetas_t, params_s, params_t) {
    .Call(`_mupp_p_mupp_impl`, thetas_s, thetas_t, params_s, params_t)
}

pder1_theta_mupp1_impl <- function(thetas_s, thetas_t, params_s, params_t, type_s = TRUE) {
    .Call(`_mupp_pder1_theta_mupp1_impl`, thetas_s, thetas_t, params_s, params_t, type_s)
}

pder1_theta_mupp_impl <- function(thetas_s, thetas_t, params_s, params_t) {
    .Call(`_mupp_pder1_theta_mupp_impl`, thetas_s, thetas_t, params_s, params_t)
}

